WebUI/EISSystem/EISSystem/Controllers/AdminDetailsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using EIS.Entities.Employee;
using EIS.Entities.SP;
using EIS.WebApp.Filters;
using EIS.WebApp.IServices;
using EIS.WebApp.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EIS.WebApp.Controllers
{
    [SessionTimeOut]
    [DisplayName("Admin Management")]
    public class AdminDetailsController : BaseController<Person>
    {
        private readonly IHostingEnvironment _environment;
        #region Declarations
        public readonly IServiceWrapper _services;
        private readonly IControllerService _controllerService;
        public static HttpResponseMessage response;
        public MyHttpContext httpContext;

        #endregion 

        #region Controller
        public AdminDetailsController(IEISService<Person> service, IControllerService controllerService, IServiceWrapper services, IHostingEnvironment environment) : base(service)
        {
            _environment = environment;
            _controllerService = controllerService;
            _services = services;
        }
        #endregion

        [DisplayName("List Of Admins")]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(bool type)
        {
            HttpResponseMessage response = _services.SP_GetEmployee.GetResponse(ApiUrl + "/api/employee/AdminData/" + type);
            //return LoadData<Person>(ApiUrl + "/api/employee/data", type, LocationId);
            string stringData = response.Content.ReadAsStringAsync().Result;
            List<SP_GetEmployee> sP_GetEmployee = JsonConvert.DeserializeObject<List<SP_GetEmployee>>(stringData);
            return Json(sP_GetEmployee);

        }
    }
}

WebUI/EISSystem/EISSystem/Controllers/PeopleController.cs
using EIS.Entities.Address;
using EIS.Entities.Employee;
using EIS.Entities.OtherEntities;
using EIS.Entities.SP;
using EIS.WebApp.Filters;
using EIS.WebApp.IServices;
using EIS.WebApp.Models;
using EIS.WebApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace EIS.WebApp.Controllers
{
    [SessionTimeOut]
    [DisplayName("Employee Management")]
    public class PeopleController : BaseController<Person>
    {
        private readonly IHostingEnvironment _environment;
        #region Declarations
        public readonly IServiceWrapper _services;
        private readonly IControllerService _controllerService;
        public static HttpResponseMessage response;
        public static List<Person> data;
        public static List<Role> rolesList;
        public MyHttpContext httpContext;

        #endregion 

        #region Controller
        [DisplayName("Employee Management")]
        public PeopleController(IEISService<Person> service, IControllerService controllerService, IServiceWrapper services, IHostingEnvironment environment) : base(service)
        {
            _environment = environment;
            _controllerService = controllerService;
            _services = services;
            HttpResponseMessage response = _services.Roles.GetResponse(ApiUrl+"/api/Employee/Designations" );
            string stringData = response.Content.ReadAsStringAsync().Result;
            rolesList = JsonConvert.DeserializeObject<List<Role>>(stringData);
        }
        #endregion

        #region Employee
        [DisplayName("List Of Employees")]
        public IActionResult Index()
        {
            ViewBag.Locations = GetLocations();
            return View();
        }
        [HttpPost]
        public IActionResult Index(bool type, int LocationId)
        {
            HttpResponseMessage response = _services.SP_GetEmployee.GetResponse(ApiUrl + "/api/employee/Data/"+type+"/"+LocationId);
            //return LoadData<Person>(ApiUrl + "/api/employee/data", type, LocationId);
            string stringData = response.Content.ReadAsStringAsync().Result;
            List<SP_GetEmployee> sP_GetEmployee = JsonConvert.DeserializeObject<List<SP_GetEmployee>>(stringData);
            return Json(sP_GetEmployee);

        }
        public IActionResult Profile(string PersonId)
        {
            response = _services.Employee.GetResponse(ApiUrl+"/api/employee/Profile/" + PersonId + "" );
            string stringData = response.Content.ReadAsStringAsync().Result;
            Person data = JsonConvert.DeserializeObject<Person>(stringData);
            data.FirstName = MakeFirstCapital(data.FirstName);
            data.MiddleName = MakeFirstCapital(data.MiddleName);
            data.LastName = MakeFirstCapital(data.LastName);
            Attendance attendance = data.Attendance.Where(x => x.DateIn.Date == DateTime.Now.Date).FirstOrDefault();
            if (attendance != null)
            {
                ViewBag.TimeIn = attendance.TimeIn;
                ViewBag.TimeOut = attendance.TimeOut.GetValueOrDefault();
                ViewBag.TotalHrs = attendance.TotalHours.GetValueOrDefault();
                ViewBag.EstimatedTimeOut = attendance.TimeIn + new TimeSpan(9, 0, 0);
            }
            else
            {
                ViewBag.TimeIn = new TimeSpan();
                ViewBag.TimeOut = new TimeSpan();
                ViewBag.TotalHrs = new TimeSpan();
                ViewBag.EstimatedTimeOut = new TimeSpan();
            }
            if (data.PermanentAddress == null)
                data.PermanentAddress = new Permanent() { PersonId = data.Id };
            var cur = new Current() { PersonId = data.Id };
            if (data.CurrentAddress == null)
                data.CurrentAddress = cur;
            Response.StatusCode = (int)response.StatusCode;
            return View("Profile", data);
        }
        [DisplayName("Create Employee")]
        public IActionResult Create()
        {
            ViewBag.Locations = GetLocations();
            ViewBag.WeeklyOffs = GetWeeklyOffs();
            ViewBag.Designations = rolesList;
            var data = from p in EmployeeData()
                       where p.Role.Name != "Employee"
                       select new Person { Id = p.Id, FirstName = p.FirstName + " " + p.LastName + " (" + p.Role.Name + ")" };
            ViewBag.Persons = data;
            ViewBag.Dob = DateTime.Now.ToShortDateString();
            return View("CreateEmployee");
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateEmployee createEmployee, IFormFile file)
        {
            if (createEmployee.people.DateOfBirth != null)
            {
                var d = DateTime.Parse(createEmployee.people.DateOfBirth.ToString());
                createEmployee.people.DateOfBirth = d;
            }
            if (createEmployee.people.RoleId == 0) ModelState.AddModelError("RoleId", "Please Select Role");
            if (createEmployee.people.LocationId == 0) ModelState.AddModelError("LocationId", "Please Select Location");
            if (createEmployee.people.WeeklyOffId == 0) ModelState.AddModelError("WeeklyOffId", "Please Select Weekly Off Type");
            var tId = GetSession().TenantId;
            ViewBag.Locations = GetLocations();
            ViewBag.WeeklyOffs = GetWeeklyOffs();
            //var tId = Cache.GetStringValue("TenantId");
            ViewBag.Designations = rolesList;

            var data = from p in EmployeeData()
                       where p.Role.Name != "Employee"
                       select new Person { Id = p.Id, FirstName = p.FirstName + " " + p.LastName + " (" + p.Role.Name + ")" };
            ViewBag.Persons = data;

            if (ModelState.IsValid)
            {
                createEmployee.people.CreatedBy = Convert.ToInt32(GetSession().PersonId);
                string rootPath = _environment.WebRootPath;
                string filePath = "//EmployeeData//" + tId + createEmployee.people.EmployeeCode + "//Image//";
                if (!Directory.Exists(rootPath + "//EmployeeData//"))
                {
                    Directory.CreateDirectory(rootPath + "//EmployeeData//");
                }
                if (!Directory.Exists(rootPath + filePath))
                {
                    Directory.CreateDirectory(rootPath + filePath);
                }
                else
                {
                    string[] files = Directory.GetFiles(rootPath + filePath);
                    if (files.Length > 0)
                    {
                        for (int i = 0; i < files.Length; i++)
                        {
                            System.IO.File.Delete(files[i]);
                        }
                    }
                }
                string uploadPath = rootPath + filePath;
                if (file != null && file.Length > 0)
                {
                    var fileExtension = Path.GetExtension(file.FileName).ToLower();

                    if ((fileExtension == ".gif" || fileExtension == ".png" || fileExtension == ".bmp" || fileExtension == ".jpeg" || fileExtension == ".jpg") && file.Length <= 500000)
                    {

                        var fileName = createEmployee.people.FirstName + "_" + Guid.NewGuid().ToString().Substring(0, 4) + fileExtension;
                        using (var fileStream = new FileStream(Path.Combine(uploadPath, fileName), FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);
                            createEmployee.people.Image = fileName;
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("Image", "Please select Image of type GIF, PNG, JPG, JPEG and BMP and size must be below 500 kb");
                    }
                }
                else
                {
                    System.IO.File.Copy(rootPath + "//EmployeeData//DefaultImage//Default.png", uploadPath + "Default.png");
                    createEmployee.people.Image = "Default.png";

                }
                if (string.IsNullOrEmpty(createEmployee.people.MiddleName))
                {
                    createEmployee.people.MiddleName = "";
                }

                createEmployee.people.CreatedDate = DateTime.Now.Date;
                HttpResponseMessage response = _services.Employee.PostResponse(ApiUrl + "/api/employee/" + 0, createEmployee.people);
                string data1 = response.Content.ReadAsStringAsync().Result;
                Person pdata = JsonConvert.DeserializeObject<Person>(data1);
                CreatePermanentAddress(pdata.Id,pdata.EmployeeCode,createEmployee.permanent);
                if(createEmployee.current.Address!=null)
                {
                    CreateCurrentAddress(pdata.Id, pdata.EmployeeCode, createEmployee.current);
                }
                CreateEmergencyAddress(pdata.Id, pdata.EmployeeCode, createEmployee.emergencyAddress);
                if (response.IsSuccessStatusCode == true)
                {
                    ViewBag.Message = "Record has been successfully saved.";
                    TempData["success"] = "Record created successfully.";
                    return RedirectToAction("Index");
                }
            }
            if (file != null)
            {
                ModelState.AddModelError("Image", "Please upload the file");
                ViewBag.ImageExist = "Validation failed... Please Upload the file again";
            }
            

WebUI/EISSystem/EISSystem/Views/AdminDetails/Index.cshtml
@using EIS.WebApp.Services
@model IEnumerable<EIS.Entities.Employee.Person>


<head>
    <title>List of Admins</title>
    <link href="~/Ems/css/responsive.dataTables.min.css" rel="stylesheet" />
    <link href="~/Ems/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Ems/css/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/css/customStyle.css" rel="stylesheet" />
    <style>
        li:hover {
            cursor: pointer;
        }

        .dataTables_wrapper .myexport .dt-buttons {
            float: right;
        }

        .ajax-loader {
            visibility: hidden;
            position: absolute;
            z-index: +100 !important;
            width: 80%;
            height: 80%;
        }

        .container-fluid {
            padding-left: 0px;
            padding-right: 0px;
        }

        .row {
            padding-bottom: 0px;
        }

        .ajax-loader img {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        table.dataTable td {
            margin-left: 0;
            margin-right: auto;
            padding: 3px 10px;
            width: 1px;
            white-space: nowrap;
        }

        .clearfix #empinfo {
            margin-top: 10px;
        }
    </style>
</head>

@{
    string rootPath = MyHttpContext.AppBaseUrl;
    string APIURL = MyHttpContext.APIBaseURL;
    if (ViewBag.Message != null)
    {
        <script>
            bootbox.alert({
                message: "@ViewBag.Message"
            });
        </script>
        ViewBag.Message = null;
    }
}
<div class="ajax-loader">
    <img src="~/gif/Spinner.gif" />
</div>
<div class="container-fluid">
    <div class="block-header">
        <div class="row">
            <div class="col-md-12">
                <HeaderWithButton header-name="List of Admins" btn-href="location.href='@rootPath/People/Create'" btn-text="Create" icon-name="person_add"></HeaderWithButton>
            </div>
        </div>
    </div>

    <div class="row clearfix">
        <div class="row">
            <div class="col-md-9" style="height:50px">
                @*<div class="col-md-4 col-sm-6 col-xs-12">
                    <select id="locations" asp-items="@(new SelectList(@ViewBag.Locations,"Id","LocationName"))" class="form-control show-tick">
                        <option value="0">All</option>
                    </select>
                </div>*@
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <select class="form-control show-tick" id="select">
                        <option id="active" value="active">Active</option>
                        <option id="inActive" value="inActive">InActive</option>
                    </select>
                </div>

            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="empinfo" style="margin-top:0px">
            <div class="card">
                <div class="body">
                    <div class="table-responsive">
                        <table id="example" class="table table-striped table-bordered table-hover" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Actions</th>
                                    <th>Location</th>
                                    <th>Employee Code</th>
                                    <th>Name</th>
                                    <th>Image</th>
                                    <th>Gender</th>
                                    <th>Birth Date</th>
                                    <th>Mobile Number</th>
                                    <th>Email Address</th>
                                    <th>Joining Date</th>
                                    <th>Created By</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var result = null;
     $(document).ready(function () {
        if ('@TempData["success"]' != '') {
            bootbox.alert({
                message: '@TempData["success"]'
            });
         }
         result = getCreatedBy();
        var b = true;
        generateReport(b,0);
    });
    $('#example').on('click', 'a.inactive', function (e) {
        e.preventDefault();
        var id = $(this).attr("id");
        var message = "Do you want to DeActivate this record ?";
        bootbox.confirm(message, function (result) {
            if (result == true) {
                $.ajax({
                    type: "GET",
                    url: '@Url.Action("DeleteConfirmed", "People")?id=' + id,
                    success: function () {
                        bootbox.alert("Record DeActivated successfully!", function () {
                            location.href = '@Url.Action("Index", "People")';
                        });
                    },
                    error: function (xhr, status, error) {
                        if (xhr.status == 401) {
                            bootbox.alert("Access denied..Unable to DeActivate the Record");
                        } else {
                            bootbox.alert("Unable to DeActivate the Record");
                        }
                    }
                });
            }
        });
    });
    $('#example').on('click', 'a.active', function (e) {
        e.preventDefault();
        var id = $(this).attr("id");
        var message = "Do you want to Activate Employee record ?"
        bootbox.confirm(message, function (result) {
            if (result == true) {
                $.ajax({
                    type: "GET",
                    url: '@Url.Action("ActivateEmployee", "People")?EmployeeCode=' + id,
                    data: null,
                    success: function () {
                        bootbox.alert("Record Activated successfully!", function () {
                            location.href = '@Url.Action("Index", "People")';
                        });
                    },
                    error: function () {
                        bootbox.alert("Unable to Activate Data");
                    }
                });
            }
        });
    });
    $('#locations').on('change', function () {
        var c = $('#locations').val();
        var v = $('#select').val();
        if (v == "active") {
            b = true;
        }
        else if (v == "inActive") {
            b = false;
        }
        generateReport(b, c);
    });
    $('#select').on('change', function () {
        var c = $('#locations').val();
        var v = $('#select').val();
        var b;
        if (v == "active") {
            b = true;
            generateReport(b,c);
        }
        else if (v == "inActive") {
            b = false;
            generateReport(b,c);
        }
    });
    function generateReport(b,c) {
        $.ajax({
            "url": '@Url.Action("Index", "AdminDetails")?type=' + b,
            "type": "POST",
            "datatype": "json",
            beforeSend: function () {
                $('.ajax-loader').css("visibility", "visible");
            },
            success: function (data) {
                var array = [];
                var action;
                var activeStatus;
                for (var i = 0; i < data.length; i++) {
                    var image = data[i].Image;
                    activeStatus = data[i].IsActive;
                    var dob = moment(data[i].DateOfBirth).format("DD MMM YYYY");
                    var joinDate = moment(data[i].JoinDate).format("DD MMM YYYY");
                    var path = '@MyHttpContext.AppBaseUrl/EmployeeData/1' + data[i].EmployeeCode + '/Image/' + image;
                    var defaultPath = '@MyHttpContext.AppBaseUrl/EmployeeData/DefaultImage/Default.png';
                    image = '<img src="' + path + '" onerror="if (this.src!=\'' + defaultPath + '\') this.src=\'' + defaultPath +'\';" style="height:40px; width:40px">';

                    if (activeStatus == true) {
                        action = '<div class="dropdown"> <button class="btn btn-primary dropdown-toggle waves-effect" type="button" data-toggle="dropdown"><i class="material-icons">build</i></button><ul class="dropdown-menu "><li><a href="@Url.Action("Profile","People")?PersonId=' + data[i].EmployeeCode + '">Profile</a></li><li><a class="inactive" id=' + data[i].EmployeeCode + '>DeActivate</a></li></ul></div>';
                    } else {
                        action = '<div class="dropdown"> <button class="btn btn-primary dropdown-toggle waves-effect" type="button" data-toggle="dropdown"><i class="material-icons">build</i></button><ul class="dropdown-menu "><li><a class="active" id=' + data[i].EmployeeCode + '>Activate</a></li></ul></div>';
                    }

                    array.push([action, data[i].LocationName, data[i].EmployeeCode, DecorateString(data[i].FullName), image, data[i].Gender, dob, data[i].MobileNumber, data[i].EmailAddress, joinDate, data[i].CreatedBy]);
                }

                $('#example').DataTable().destroy();
                $('#example').DataTable({
                    sDom: '<"myexport"B>ifrtlp',
                    order:[1,'asc'],
                    buttons: [
                        {
                            extend: 'pdfHtml5',
                            title: 'EMPLOYEE REPORT',
                            text: 'PDF',
                            titleAttr: 'Export to Pdf',
                            exportOptions: {
                                columns: [2, 3, 5, 6, 7, 8, 9]
                            }
                        },
                        {
                            extend: 'excel',
                            title: 'EMPLOYEE REPORT',
                            text: 'Excel',
                            titleAttr: 'Export to Excel',
                            exportOptions: {
                                columns: [2, 3, 5, 6, 7, 8, 9]
                            }
                        },
                        {
                            extend: 'print',
                            title: 'EMPLOYEE REPORT',
                            text: 'Print',
                            titleAttr: 'Export to Print',
                            exportOptions: {
                                columns: [2, 3, 5, 6, 7, 8, 9]
                            }
                        }
                    ],
                    data: array
                });
            },
            complete: function () {
                $('.ajax-loader').css("visibility", "hidden");
            }
        });
    }
    function getCreatedBy() {
        var result = null;
        $.ajax({
            type: "GET",
            async: false,
                    url: '@APIURL/api/Employee/CreatedBy',
                    data: null,
            success: function (data) {
                result = data;
                    }
        });
        return result;
    }

    function getCreatedname(result,pid) {
        $.each(result, function (i, item){
            if (result[i].key == pid) {
               value= result[i].value;
            }
        })
        return value;
    }
    $('#example').on('shown.bs.collapse', function () {
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
</script>
<script src="~/lib/bootstrap/dist/js/bootbox.js"></script>
<script src="~/Ems/js/jquery.dataTables.min.js"></script>
<script src="~/Ems/js/dataTables.buttons.min.js"></script>
<script src="~/Ems/js/buttons.flash.min.js"></script>
<script src="~/Ems/js/jszip.min.js"></script>
<script src="~/Ems/js/pdfmake.min.js"></script>
<script src="~/Ems/js/vfs_fonts.js"></script>
<script src="~/Ems/js/buttons.html5.min.js"></script>
<script src="~/Ems/js/buttons.print.min.js"></script>
<script src="~/Ems/js/dataTables.responsive.min.js"></script>
<script src="~/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>