WebUI/EISSystem/EISSystem/Controllers/HolidayController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using EIS.Entities.Hoildays;
using EIS.WebApp.Filters;
using EIS.WebApp.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EIS.WebApp.Controllers
{
    [SessionTimeOut]
    [DisplayName("Holidays")]
    public class HolidayController : BaseController<Holiday>
    {
        public HolidayController(IEISService<Holiday> service) : base(service)
        {

        }
        // GET: /<controller>/
        [DisplayName("List Of Holidays")]
        public IActionResult Index()
        {
            ViewBag.Locations = GetLocations();
            return View();
        }

        [ActionName("Index")]
        [HttpPost]
        public IActionResult GetIndex(int id)
        {
            return LoadData<Holiday>(ApiUrl + "/api/Holiday/GetHolidays", null, id);
        }
        [DisplayName("Show Holidays")]
        public IActionResult EmployeeHolidays()
        {
            HttpResponseMessage response = _service.GetResponse(ApiUrl + "api/Holiday/"+GetSession().PersonId);
            string stringData = response.Content.ReadAsStringAsync().Result;
            List<Holiday> data = JsonConvert.DeserializeObject<List<Holiday>>(stringData);
            return View(data);
        }
        [DisplayName("Add Holiday")]
        public IActionResult AddHoliday()
        {
            ViewBag.Locations = GetLocations();
            Holiday holiday = new Holiday();
            return PartialView("AddHoliday", holiday);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddHoliday(Holiday holiday)
        {
            ViewBag.Locations = GetLocations();
            if (holiday.LocationId == 0)
            {
                ModelState.AddModelError("LocationId","Please select location");
            }
            if (ModelState.IsValid)
            {
                holiday.CreatedBy = Convert.ToInt32(GetSession().PersonId);
                ViewBag.Locations = GetLocations();
                holiday.CreatedDate = DateTime.Now.Date;
                holiday.UpdatedDate = DateTime.Now.Date;
                holiday.IsActive = true;
                HttpResponseMessage response = _service.PostResponse(ApiUrl + "/api/Holiday/"+0, holiday);
                string stringData = response.Content.ReadAsStringAsync().Result;

                if (response.IsSuccessStatusCode == true)
                {
                    return View();
                }
                else
                {
                    dynamic data = JObject.Parse(stringData);
                    var Message = JsonConvert.DeserializeObject(response.Content.ReadAsStringAsync().Result);
                    string error = data.Date.ToString();
                    error = error.Replace("[", null); error = error.Replace("]", null);

                    ModelState.AddModelError("Date", error);
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                }
            }
            else Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return PartialView("AddHoliday", holiday);
        }
        [DisplayName("Update Holiday")]
        public IActionResult EditHoliday(int HolidayId)
        {
            ViewBag.Locations = GetLocations();
            string stringData = _service.GetResponse(ApiUrl + "/api/Holiday/GetHolidayById/" + HolidayId + "").Content.ReadAsStringAsync().Result;
            Holiday holiday = JsonConvert.DeserializeObject<Holiday>(stringData);
            return PartialView("EditHoliday", holiday);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditHoliday(Holiday holiday)
        {
            ViewBag.Locations = GetLocations();
            if (holiday.LocationId == 0)
            {
                ModelState.AddModelError("LocationId", "Please select location");
            }
            if (ModelState.IsValid)
            {
                holiday.UpdatedBy = Convert.ToInt32(GetSession().PersonId);
                ViewBag.Locations = GetLocations();
                holiday.UpdatedDate = DateTime.Now.Date;
                holiday.IsActive = true;
                HttpResponseMessage response = _service.PostResponse(ApiUrl + "/api/Holiday/"+holiday.Id, holiday);
                string stringData = response.Content.ReadAsStringAsync().Result;

                if (response.IsSuccessStatusCode == true)
                {
                    return View();
                }
                else
                {
                    dynamic data = JObject.Parse(stringData);
                    var Message = JsonConvert.DeserializeObject(response.Content.ReadAsStringAsync().Result);
                    string error = data.Date.ToString();
                    error = error.Replace("[", null); error = error.Replace("]", null);

                    ModelState.AddModelError("Date", error);
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                }
            }
            else Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return PartialView("EditHoliday", holiday);
        }
        [DisplayName("Delete Holiday")]
        public void Delete(int id)
        {
            HttpResponseMessage response = _service.PostResponse(ApiUrl + "/api/Holiday/DeleteHoliday/" + id, null);
            if (response != null)
            {

            }

        }
        //[DisplayName("Activate Holiday")]
        //public IActionResult ActivateLocation(int id)
        //{
        //    HttpResponseMessage response = _service.GetResponse(ApiUrl + "/api/Location/ActivateLocation/" + id + "");
        //    if (response.IsSuccessStatusCode)
        //        ViewBag.Message = "Location activated successfully!";
        //    return RedirectToAction("Index", "Location");
        //}
    }
}

WebUI/EISSystem/EISSystem/Views/Holiday/AddHoliday.cshtml
@using EIS.Entities.Hoildays
@using EIS.Entities.Enums;
@model Holiday
<!-- Modal -->
<style type="text/css">
    .form-group.required .control-label:after {
        color: #d00;
        content: "*";
        position: relative;
    }
</style>
<link href="~/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
<link href="~/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap-datetimepicker1.css" rel="stylesheet" />
<link href="~/css/customStyle.css" rel="stylesheet" />

<div id="md" class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <HeaderWithButton class="modal-title" header-name="Add Holiday"></HeaderWithButton>
            <button type="button" class="close" data-dismiss="modal">×</button>
        </div>
        <div class="modal-body">
            <form name="cp" id="cp" asp-action="AddHoliday" asp-controller="Holiday" method="post">

                <input type="hidden" asp-for="Id" value="0" />
                <div class="form-group required">
                    <label class="control-label" asp-for="LocationId">Location : </label>
                    <select id="did" data-size="5" asp-for="LocationId" asp-items="@(new SelectList(@ViewBag.Locations,"Id","LocationName"))" class="form-control show-tick">
                        <option value="0">-- Select Location --</option>
                    </select>
                    <span asp-validation-for="LocationId" class="text-danger"></span>
                </div>
                <div class="form-group required">
                    <label class="control-label" asp-for="Date">Holiday Date</label>
                    <div class="form-line">
                        <input class="form-control" type="text" asp-for="Date" id="inputdate" placeholder="Select Date" autocomplete="off" />
                    </div>
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group required">
                    <label class="control-label">Holiday</label>
                    <div class="form-line">
                        <input asp-for="Vacation" class="form-control" />
                    </div>

                    <span asp-validation-for="Vacation" class="text-danger"></span>
                </div>
                <div class="modal-footer">
                    <button id="btnSubmit" name="btnSubmit" type="button" class="btn btn-link waves-effect">Save</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>

    </div>
</div>

<script src="~/plugins/bootstrap-select/js/bootstrap-select.js"></script>

<script src="~/plugins/momentjs/moment.js"></script>
<script src="~/Ems/js/bootstrap-datetimepicker.min.js"></script>

<script src="~/js/pages/ui/modals.js"></script>
<script src="~/plugins/bootbox/bootbox.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script>
    $('#did').selectpicker();
    var d = new Date();
    d.setDate(d.getDate());
    var defaultDate = moment().toDate();
    $('#inputdate').datetimepicker({
        format: "DD/MMM/YYYY",
        defaultDate: d
    });
    $('#btnSubmit').click(function () {
        var form = $("#cp");
        $.validator.unobtrusive.parse(form);
        if (form.valid()) {
            bootbox.confirm({
                message: "Are you sure to add new Holiday?",
                buttons: {
                    confirm: {
                        label: 'Yes',
                        className: 'btn-success'
                    },
                    cancel: {
                        label: 'No',
                        className: 'btn-danger'
                    }
                },
                callback: function (result) {
                    if (result == true) {
                        var d = form.serialize();
                        $.ajax({
                            url: '@Url.Action("AddHoliday", "Holiday")',
                            type: 'POST',
                            data: d,
                            success: function (data) {
                                bootbox.alert({
                                    message: "Holiday Added Successfully!",
                                    callback: function () {
                                        window.parent.location.reload();
                                    }
                                });
                            },
                            error: function (data) {
                                $("#md").replaceWith(data.responseText);
                                $('#inputdate').datetimepicker({
                                    format: "DD/MMM/YYYY"
                                });
                            }
                        });
                    }
                }
            });

        }
        return false;
    });
</script>

WebUI/EISSystem/EISSystem/Views/Holiday/EditHoliday.cshtml
@using EIS.Entities.Hoildays
@using EIS.Entities.Enums;
@using System.Globalization;
@model Holiday
<!-- Modal -->
<link href="~/css/customStyle.css" rel="stylesheet" />
<style type="text/css">
    .form-group.required .control-label:after {
        color: #d00;
        content: "*";
        position: relative;
    }
</style>
<link href="~/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css" rel="stylesheet" />
<div id="md" class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <HeaderWithButton class="modal-title" header-name="Update Holiday"></HeaderWithButton>
            <button type="button" class="close" data-dismiss="modal">×</button>
        </div>
        <div class="modal-body">
            <form name="cp" id="cp" asp-action="EditHoliday" asp-controller="Holiday" method="post">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="CreatedBy" />
                <input type="hidden" asp-for="CreatedDate" />
                <input type="hidden" asp-for="RowVersion" />

                <div class="form-group required">
                    <label class="control-label" asp-for="LocationId">Location : </label>
                    <select id="did" asp-for="LocationId" asp-items="@(new SelectList(@ViewBag.Locations,"Id","LocationName"))" class="form-control show-tick">
                        <option value="0">-- Select Location --</option>
                    </select>
                    <span asp-validation-for="LocationId" class="text-danger"></span>
                </div>
                <div class="form-group required">
                    <label class="control-label" asp-for="Date">Holiday Date</label>
                    <div class="form-line">
                        <input class="form-control" type="text" asp-for="Date" id="inputdate1" placeholder="select Date" autocomplete="off" />
                    </div>
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group required">
                    <label class="control-label">Holiday</label>
                    <div class="form-line">
                        <input asp-for="Vacation" class="form-control" />
                    </div>

                    <span asp-validation-for="Vacation" class="text-danger"></span>
                </div>
                <div class="modal-footer">
                    <button id="btnSubmit" name="btnSubmit" type="button" class="btn btn-link waves-effect">Save</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>

    </div>
</div>
<script src="~/plugins/momentjs/moment.js"></script>
<script src="~/Ems/js/moment.min.js"></script>
<script src="~/Ems/js/bootstrap-datetimepicker.min.js"></script>
<script src="~/lib/bootstrap/dist/js/moment1.js"></script>
<script src="~/js/pages/ui/modals.js"></script>
<script src="~/plugins/bootbox/bootbox.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script>
    $(document).ready(function () {
        var d1 = document.getElementById("inputdate1").value;
        var cultureInfo = '@CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern.ToUpper()';
        var dt = moment(d1, cultureInfo).format("DD/MMM/YYYY");

        if (dt == "Invalid date") {
            $("#inputdate1").val(d1);
        } else {
            $("#inputdate1").val(dt);
        }
    })
    $('#btnSubmit').click(function () {
        var form = $("#cp");
        $.validator.unobtrusive.parse(form);
        if (form.valid()) {
            bootbox.confirm({
                message: "Are you sure to update Holiday?",
                buttons: {
                    confirm: {
                        label: 'Yes',
                        className: 'btn-success'
                    },
                    cancel: {
                        label: 'No',
                        className: 'btn-danger'
                    }
                },
                callback: function (result) {
                    if (result == true) {
                        var d = form.serialize();
                        $.ajax({
                            url: '@Url.Action("EditHoliday", "Holiday")',
                            type: 'POST',
                            data: d,
                            success: function (data) {
                                bootbox.alert({
                                    message: "Holiday Updated Successfully!",
                                    callback: function () {
                                        window.parent.location.reload();
                                    }
                                });
                            },
                            error: function (data) {
                                $("#md").replaceWith(data.responseText);
                                $('#inputdate1').datetimepicker({
                                    format: "DD-MMM-YYYY"
                                });
                            }
                        });
                    }
                }
            });

        }
        return false;
    });
</script>

WebUI/EISSystem/EISSystem/Views/Holiday/Index.cshtml
@model IEnumerable<EIS.Entities.Hoildays.Holiday>


<link href="~/Ems/css/jquery.dataTables.min.css" rel="stylesheet" />

<link href="~/Ems/css/responsive.dataTables.min.css" rel="stylesheet" />

<html>
<head>
    <title>Holidays</title>
    <link href="~/Ems/css/responsive.dataTables.min.css" rel="stylesheet" />
    <link href="~/Ems/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/Ems/css/buttons.dataTables.min.css" rel="stylesheet" />
    <link href="~/css/customStyle.css" rel="stylesheet" />
    <style>
        .dataTables_wrapper .myexport .dt-buttons {
            float: right;
        }

        li:hover {
            cursor: pointer;
        }

        th, td {
            white-space: nowrap;
        }

        .ajax-loader {
            visibility: hidden;
            position: absolute;
            z-index: +100 !important;
            width: 80%;
            height: 80%;
        }

            .ajax-loader img {
                position: fixed;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
            }

        table.dataTable td {
            margin-left: 0;
            margin-right: auto;
            padding: 3px 10px;
            width: 1px;
            white-space: nowrap;
        }

        .container-fluid {
            padding-left: 0px;
            padding-right: 0px;
        }

        #holidays {
            margin-top: 20px;
        }

        #locations {
            width: 60%;
        }
    </style>
</head>
<body>
    <div class="ajax-loader">
        <img src="~/gif/Spinner.gif" />
    </div>
    <div id="modal-placeholder" class="modal fade" role="dialog" data-url="@Url.Action("AddHoliday")"></div>
    <div id="modal-placeholder-editholiday" class="modal fade" role="dialog" data-url="@Url.Action("EditHoliday")"></div>
    @*BootStrap Model*@
    <div class="container-fluid">
        <div class="block-header">
            <HeaderWithButton btn-id="btnModal" header-name="Holidays" btn-text="Add Holiday" icon-name="add"></HeaderWithButton>
        </div>
        <div class="row clearfix">
            <div class="col-md-4 col-sm-6 col-xs-12">
                <select id="locations" asp-items="@(new SelectList(@ViewBag.Locations,"Id","LocationName"))" class="form-control show-tick">
                    <option value="0">All</option>
                </select>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="holidays">
                <div class="card">
                    <div class="body">
                        <div class="table-responsive">
                            <table id="example" class="table table-striped table-bordered table-hover" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Location</th>
                                        <th>Date</th>
                                        <th>Day</th>
                                        <th>Holiday</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>


<script src="~/lib/bootstrap/dist/js/bootbox.js"></script>
<script>
    $(document).ready(function () {
        GenerateReport(0);
    });
    $('#locations').on('change', function () {
        var c = $('#locations').val();
        GenerateReport(c);
    });
    function GenerateReport(c) {
                $.fn.dataTable.ext.errMode = 'none';
        $('#example').on('error.dt', function () {
            bootbox.alert('<h4>Unable to load data from Server. Please try after sometime</h4>');
        }).DataTable();
        $('#example').DataTable().destroy();
        $('#example tbody').empty();
        var dTable = $('#example').DataTable({
            sDom: '<"myexport"B>irtlp',
            paging:false,
            fixedColumns: true,
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            order:[1,'asc'],
            buttons: [
                {
                    extend: 'pdfHtml5',
                    title: 'Holidays',
                    text: 'PDF',
                    titleAttr: 'Export to PDF',
                    exportOptions: {
                        columns: [0,1,2, 3]
                    }
                },
                {
                    extend: 'excel',
                    title: 'Holidays',
                    text: 'Excel',
                    titleAttr: 'Export to Excel ',
                    exportOptions: {
                        columns: [0,1,2, 3]
                    }
                },
                {
                    extend: 'print',
                    title: 'Holidays',
                    text: 'Print',
                    titleAttr: 'Print',
                    exportOptions: {
                        columns: [0,1,2, 3]
                    }
                }
            ],
            ajax: {
                //"url": "/Leave/PastLeaves",
                "url": '@Url.Action("Index", "Holiday")?id='+c,
                "type": "POST",
                "datatype": "json",
                beforeSend: function () {
                    $('.ajax-loader').css("visibility", "visible");
                },
                complete: function () {
                    $('.ajax-loader').css("visibility", "hidden");
                }

            },
            "columns": [
                {
                    "data": "Location.LocationName","name": "Location.LocationName", "autoWidth": true, render: function (data, type, row) {
                        return row.Location.LocationName;
                    }
                },
                {
                    "data": "Date", "name": "Date" ,"autoWidth": true, render: function (data) {
                        data = moment(data).format('DD MMM YYYY');
                        return data;
                    }
                },
                {
                    "data": "Date", "name": "Date", "autoWidth": true, render: function (data) {
                        var days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
                        var d = new Date(data);
                        var dayName = days[d.getDay()];
                        return dayName;
                    }
                },
                {
                    "data": "Vacation", "name": "Vacation", "autoWidth": true, render: function (data) {
                        return data;
                    }
                },
                {
                    data: null, "autoWidth": true, render: function (data, type, row) {
                        return '<div class="dropdown"> <button class="btn btn-primary dropdown-toggle waves-effect" type="button" data-toggle="dropdown"><i class="material-icons">build</i></button><ul class="dropdown-menu"><li><a  onclick="fun(' + row.Id + ');">Edit</a></li><li><a class="inactive" id=' + row.Id + '>Delete</a></li></ul></div>';
                    }
                }
            ]
        });
    }
    function fun(c) {
        var url = $("#modal-placeholder-editholiday").data('url');
        url = url + '?HolidayId=' + c;
        $.get(url, function (data) {
            $("#modal-placeholder-editholiday").html(data);
            $("#modal-placeholder-editholiday").modal({ backdrop: 'static', keyboard: false },'show');
            $('#inputdate1').datetimepicker({
                format: "DD/MMM/YYYY"
            });
        }).fail(function (xhr, status, error) {
            if (xhr.status == 401) {
                bootbox.alert("<h4>Access denied..Unable to Edit the Record</h4>");
            } else {
                bootbox.alert("<h4>Unable to Edit the Record</h4>");
            }
        });
    }
    $("#btnModal").click(function () {
        var url = $("#modal-placeholder").data('url');
        $.get(url, function (data) {
            $("#modal-placeholder").html(data);
            $("#modal-placeholder").modal({ backdrop: 'static', keyboard: false },'show');
            $('#inputdate').datetimepicker({
                format: "DD/MMM/YYYY"
            });
        }).fail(function (xhr, status, error) {
            if (xhr.status == 401) {
                bootbox.alert("<h4>Access denied..Unable to add the Record</h4>");
            } else {
                bootbox.alert("<h4>Unable to add the Record</h4>");
            }
        });
    });
       $('#example').on('click', 'a.inactive', function (e) {
        e.preventDefault();
        var id = $(this).attr("id");
        var message = "<h4>Do you want to remove this holiday ?</h4>"
       bootbox.confirm(message, function (result) {
            if (result == true) {
                $.ajax({
                    type: "GET",
                    url: '@Url.Action("Delete", "Holiday")?id=' + id,
                    success: function () {
                        bootbox.alert("<h4>Record deleted successfully!</h4>", function () {
                            location.href = '@Url.Action("Index", "Holiday")';
                        });
                    },
                    error: function (xhr, status, error) {
                        if (xhr.status == 401) {
                            bootbox.alert("<h4>Access denied..Unable to Delete the Record</h4>");
                        } else {
                            bootbox.alert("<h4>Unable to Delete the Record</h4>");
                        }
                    }
                });
            }
        });
    });
    $('#example').on('shown.bs.collapse', function () {
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
</script>

<script src="~/Ems/js/jquery.dataTables.min.js"></script>
<script src="~/Ems/js/dataTables.buttons.min.js"></script>
<script src="~/Ems/js/buttons.flash.min.js"></script>
<script src="~/Ems/js/jszip.min.js"></script>
<script src="~/Ems/js/pdfmake.min.js"></script>
<script src="~/Ems/js/vfs_fonts.js"></script>
<script src="~/Ems/js/buttons.html5.min.js"></script>
<script src="~/Ems/js/buttons.print.min.js"></script>
<script src="~/Ems/js/dataTables.responsive.min.js"></script>
<script src="~/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js"></script>