WebUI/EISSystem/EISSystem/Controllers/LeaveController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using EIS.Entities.Employee;
using EIS.Entities.Leave;
using EIS.Entities.Models;
using EIS.Entities.SP;
using EIS.WebApp.Filters;
using EIS.WebApp.Hubs;
using EIS.WebApp.IServices;
using EIS.WebApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Newtonsoft.Json;

namespace EIS.WebApp.Controllers
{
    [SessionTimeOut]
    [DisplayName("Leave Management")]
    public class LeaveController : BaseController<EmployeeLeaves>
    {
        #region Declarations
        HttpResponseMessage response;
        List<LeaveCredit> data;
        private IServiceWrapper _services;
        private IHubContext<PendingLeavesCountHub> _hubContext;
        #endregion

        #region Controller
        public LeaveController(IServiceWrapper services, IEISService<EmployeeLeaves> service, IHubContext<PendingLeavesCountHub> hubContext) : base(service)
        {
            _services = services;
            _hubContext = hubContext;
        }
        #endregion

        #region Requests
        [DisplayName("View All Requests")]
        public IActionResult EmployeeLeaveHistory(string Status)
        {
            ViewBag.Status = Status;
            ViewBag.Locations = GetLocations();
            return View();
        }

        [ActionName("EmployeeLeaveHistory")]
        [HttpPost]
        public IActionResult GetEmployeeLeaveHistory(int locationId, string employeeId, string leaveType, string type, string value, bool status)
        {
            int month = 0;
            int year = 0;
            string[] dateSplit = new string[1];
            if (type == "month")
            {
                dateSplit = value.Split('/');
                month = Convert.ToInt32(dateSplit[0]);
                year = Convert.ToInt32(dateSplit[1]);

            }
            else
                if (type == "year")
            {
                year = Convert.ToInt32(value);
            }
            HttpResponseMessage response = _service.GetResponse(ApiUrl + "/api/LeaveRequest/GetLeaveHistory/" + locationId + "/" + employeeId + "/" + month + "/" + year + "/" + leaveType + "/" + status);
            string stringData = response.Content.ReadAsStringAsync().Result;
            List<LeaveRequestViewModel> leave = JsonConvert.DeserializeObject<List<LeaveRequestViewModel>>(stringData);
            return Json(leave);
        }

        //[DisplayName("Show Employees Requests")]
        //public IActionResult LeaveRequestsUnderMe()
        //{

        //    return View();
        //}

        //[HttpPost]
        //[ActionName("LeaveRequestsUnderMe")]
        //public IActionResult GetLeaveRequestsUnderMe()
        //{
        //    int pid = Convert.ToInt32(GetSession().PersonId);
        //    ArrayList arrayData = new ArrayList();
        //    return LoadData<LeaveRequest>(ApiUrl + "/api/LeaveRequest/RequestsUnderMe/" + pid + "", null, null);
        //}

        [DisplayName("Show My Leaves")]
        public IActionResult ShowMyLeaves()
        {
            int pid = Convert.ToInt32(GetSession().PersonId);
            HttpResponseMessage response = _services.LeaveRequest.GetResponse(ApiUrl + "/api/LeaveRequest/GetAvailableCount/" + pid);
            string stringData = response.Content.ReadAsStringAsync().Result;
            int value = JsonConvert.DeserializeObject<int>(stringData);
            ViewBag.AvailableCount = value;
            return View();
        }

        [HttpPost]
        [ActionName("ShowMyLeaves")]
        public IActionResult GetMyLeaves()
        {
            int pid = Convert.ToInt32(GetSession().PersonId);
            HttpResponseMessage response = _services.LeaveRequest.GetResponse(ApiUrl + "/api/LeaveRequest/Employee/" + pid);
            string stringData = response.Content.ReadAsStringAsync().Result;
            List<SP_EmployeeLeaveRequest> leaveData = JsonConvert.DeserializeObject<List<SP_EmployeeLeaveRequest>>(stringData);
            return Json(leaveData);

        }

        [DisplayName("Request For Leave")]
        public IActionResult RequestLeave()
        {
            response = _services.LeaveRules.GetResponse(ApiUrl + "/api/LeaveCredit/GetCreditsByPerson/" + GetSession().PersonId + "/Future");
            string stringData = response.Content.ReadAsStringAsync().Result;
            data = JsonConvert.DeserializeObject<List<LeaveCredit>>(stringData).ToList();
            if (data.Count == 0)
            {
                ViewBag.Status = "NoData";
                ViewBag.ListOfPolicy = data;
            }
            else
                ViewBag.ListOfPolicy = data;
            return PartialView("RequestLeave");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RequestLeave(LeaveRequest request)
        {
            request.CreatedDate = DateTime.Now;
            request.AppliedDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                request.CreatedBy = Convert.ToInt32(GetSession().PersonId);
                request.IsActive = true;
                request.Id = 0;
                HttpResponseMessage response = _services.LeaveRequest.PostResponse(ApiUrl + "/api/LeaveRequest/" + 0 + "/Future", request);
                if (response.IsSuccessStatusCode == true)
                {
                    _hubContext.Clients.All.SendAsync("AddLeave", "");
                    return View();
                }
            }
            else Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return PartialView("RequestLeave", request);
        }
        [DisplayName("Add Leave By Hr")]
        public IActionResult AddLeaveByHr()
        {
            ViewBag.Persons = GetPersons();
            return PartialView("AddLeaveByHr");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddLeaveByHr(LeaveRequest request)
        {
            ViewBag.Persons = GetPersons();
            request.CreatedDate = DateTime.Now;
            request.AppliedDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                request.CreatedBy = Convert.ToInt32(GetSession().PersonId);
                request.IsActive = true;
                request.Id = 0;
                HttpResponseMessage response = _services.LeaveRequest.PostResponse(ApiUrl + "/api/LeaveRequest/" + 0 + "/Future", request);
                if (response.IsSuccessStatusCode == true)
                {
                    return View();
                }
            }
            else Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return PartialView("RequestLeave", request);
        }
        [DisplayName("Edit Leave Request")]
        public IActionResult EditLeaveRequest(int id, int PersonId)
        {
            response = _services.LeaveRules.GetResponse(ApiUrl + "/api/LeaveCredit/GetLeaveCreditsForEdit/" + PersonId);
            string stringData = response.Content.ReadAsStringAsync().Result;
            data = JsonConvert.DeserializeObject<List<LeaveCredit>>(stringData).ToList();
            if (data.Count == 0)
            {
                ViewBag.Status = "NoData";
                ViewBag.ListOfPolicy = data;
            }
            else
                ViewBag.ListOfPolicy = data;
            string Data = _services.LeaveRequest.GetResponse(ApiUrl + "/api/LeaveRequest/GetLeaveRequestForEdit/" + id + "").Content.ReadAsStringAsync().Result;
            LeaveRequestForEdit leave = JsonConvert.DeserializeObject<LeaveRequestForEdit>(Data);
            return PartialView("EditLeaveRequest", leave);
            //response = _services.LeaveRules.GetResponse(ApiUrl+"/api/LeavePolicy" );
            //string stringData1 = response.Content.ReadAsStringAsync().Result;
            //data = JsonConvert.DeserializeObject<List<LeaveCredit>>(stringData1);
            //ViewBag.ListOfPolicy = data;
            //string stringData = _services.LeaveRequest.GetResponse(ApiUrl+"/api/LeaveRequest/" + id + "" ).Content.ReadAsStringAsync().Result;
            //LeaveRequest leave = JsonConvert.DeserializeObject<LeaveRequest>(stringData);
            //return View(leave);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditLeaveRequest(int id, LeaveRequestForEdit request)
        {
            request.UpdatedDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                request.UpdatedBy = Convert.ToInt32(GetSession().PersonId);
                request.IsActive = true;
                LeaveRequest NewRequest = new LeaveRequest()
                {
                    Id = request.Id,
                    AppliedDate = request.AppliedDate,
                    ApprovedBy = request.ApprovedBy,
                    ApprovedDays = request.ApprovedDays,
                    Available = request.Available,
                    CreatedBy = request.CreatedBy,
                    CreatedDate = request.CreatedDate,
                    EmployeeName = request.EmployeeName,
                    FromDate = request.FromDate,
                    ToDate = request.ToDate,
                    IsActive = request.IsActive,
                    LeaveType = request.LeaveType,
                    PersonId = request.PersonId,
                    Reason = request.Reason,
                    RequestedDays = request.RequestedDays,
                    RowVersion = request.RowVersion,
                    Status = request.Status,
                    TenantId = request.TenantId,
                    TypeId = request.TypeId,
                    UpdatedBy = request.UpdatedBy,
                    UpdatedDate = request.UpdatedDate
                };
                HttpResponseMessage response = _services.LeaveRequest.PostResponse(ApiUrl + "/api/LeaveRequest/" + id + "/Null", NewRequest);

WebUI/EISSystem/EISSystem/Views/Leave/AddCredit.cshtml
@using EIS.Entities.Enums;
@using EIS.WebApp.Services
@using EIS.Entities.OtherEntities;
@using Newtonsoft.Json

@using Microsoft.AspNetCore.Http;
@using EIS.Entities.Leave
@model LeaveCredit
@{
    string APIURL = MyHttpContext.APIBaseURL;
    string cookiesdata = Context.Session.GetString("CookieData");

    CookieModel cookies = new CookieModel();
    if (cookiesdata != null)
    {
        cookies = JsonConvert.DeserializeObject<CookieModel>(cookiesdata);
    }
}
<!-- Modal -->
<style type="text/css">
    .form-group.required .control-label:after {
        color: #d00;
        content: "*";
        position: relative;
    }

    .ajax-loader {
        visibility: hidden;
        position: absolute;
        z-index: +100 !important;
        width: 80%;
        height: 80%;
    }

        .ajax-loader img {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
</style>
<link href="~/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
<link href="~/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap-datetimepicker1.css" rel="stylesheet" />
<link href="~/css/customStyle.css" rel="stylesheet" />
<div id="md" class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <HeaderWithButton class="modal-title" header-name="Add Leave Credit"></HeaderWithButton>
            <button type="button" class="close" data-dismiss="modal">×</button>
        </div>
        <div class="modal-body">
            <div class="ajax-loader">
                <img src="~/gif/Spinner.gif" />
            </div>
            <form name="cp" id="cp" asp-action="AddCredit" asp-controller="Leave" method="post">
                <input type="hidden" asp-for="Id" value="0" />
                @*<div class="form-group required">
                        <label class="control-label">Location : </label>
                        <select id="locations" asp-items="@(new SelectList(@ViewBag.Locations,"Id","LocationName"))" class="form-control show-tick">
                            <option value="0">-- Select Location --</option>
                        </select>
                        <span id="msg" class="text-danger"></span>
                    </div>*@
                <div class="form-group required">
                    <label class="control-label" asp-for="PersonId">Select Employee</label>
                    <select id="emp" data-size="5" asp-items="@(new SelectList(@ViewBag.Persons,"Id","FirstName"))" asp-for="PersonId" class="form-control show-tick" data-live-search="true"></select>
                    <span asp-validation-for="PersonId" class="text-danger"></span>
                </div>
                <div class="form-group required">
                    <label class="control-label" asp-for="LeaveId">Leave Type</label>
                    <select id="type" data-size="5" asp-items="@(new SelectList(@ViewBag.ListOfPolicy,"Id","LeaveType"))" asp-for="LeaveId" class="form-control show-tick" onchange="GetStatus();">
                        <option value="0">-- Select Leave Type --</option>
                    </select>
                    <span asp-validation-for="LeaveId" class="text-danger"></span>
                </div>
                <div class="form-group required">
                    <label class="control-label">Days to be alloted</label>
                    <div class="form-line">
                        <input id="val" asp-for="AllotedDays" maxlength="2" class="form-control" />
                    </div>
                    <span asp-validation-for="AllotedDays" class="text-danger"></span>
                </div>
                <div class="form-group required">
                    <label class="control-label">Valid From</label>
                    <div class="form-line">
                        <input class="form-control" type="text" asp-for="ValidFrom" value="" id="validFrom" placeholder="select Date" autocomplete="off" />
                    </div>
                    <span asp-validation-for="ValidFrom" class="text-danger"></span>
                </div>
                <div class="form-group required">
                    <label class="control-label">Valid To</label>
                    <div class="form-line">
                        <input class="form-control" type="text" asp-for="ValidTo" value="" id="validTo" placeholder="select Date" autocomplete="off" />
                    </div>
                    <span asp-validation-for="ValidTo" class="text-danger"></span>
                </div>
                <input id="tp" type="hidden" asp-for="LeaveType" />
                <div class="modal-footer">
                    <button id="btnSubmit" name="btnSubmit" type="button" class="btn btn-link waves-effect">Add Credit</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>

    </div>
</div>

<script src="~/plugins/momentjs/moment.js"></script>
<script src="~/Ems/js/bootstrap-datetimepicker.min.js"></script>
<script src="~/js/pages/ui/modals.js"></script>
<script src="~/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<script src="~/plugins/bootbox/bootbox.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script>
    $('#type').selectpicker();
    $('#emp').selectpicker();
    var d = new Date();
    d.setDate(d.getDate());
    var defaultDate = moment().toDate();
    $('#validFrom').datetimepicker({
        format: "DD/MMM/YYYY",
        defaultDate: d
    });
    $('#validTo').datetimepicker({
        format: "DD/MMM/YYYY",
        defaultDate: d
    });
    function GetStatus() {
        var type = $('#type').val();
        $.ajax({
            url: "@APIURL/api/LeavePolicy/GetPaidStatus/" + type,
            type: 'GET',
            success: function (data) {
                if (data == false) {
                    $("#val").prop("disabled", true);
                    $("#val").val("0");
                 }
                else {
                    $("#val").removeAttr('disabled');
                 }
            },
            error: function (data) {
            }
        });
    }
    @*function loadEmployees(loc,eid){
         $.ajax({
                type: 'GET',
                url: '@MyHttpContext.APIBaseURL/api/Employee/GetLocations/' + loc,
                success: function (data) {
                    $('#emp').empty().append('<option value="0">-- Select Employee --</option>');
                    $.each(data, function (data, value) {
                        $('#emp').append($("<option></option>").val(this.id).html(this.fullName));
                    });
                    $('#emp').val(eid);

                },
                error: function () {
                    bootbox.alert("Something went wrong..Please try after sometime");
                }
        });
    }
    function loadLeave(loc,lid){
         $.ajax({
                type: 'GET',
                url: '@MyHttpContext.APIBaseURL/api/LeavePolicy/GetPolicies/' + loc,
                success: function (data) {
                    $('#type').empty().append('<option value="0">-- Select Leave Type --</option>');
                    $.each(data, function (data, value) {
                        $('#type').append($("<option></option>").val(this.id).html(this.leaveType));
                    });
                     $('#type').val(lid);
                },
                error: function () {
                    bootbox.alert("Something went wrong..Please try after sometime");
                }
            });
    }
    $('#locations').on('change', function () {
        var loc = $('#locations').val();
        loadEmployees(loc,0);
        loadLeave(loc,0);
    });*@

    $('#btnSubmit').click(function () {
        var loc = $('#locations').val();
        var type = $('#type').val();
        var emp = $('#emp').val();
        var t = $("#type option:selected").text();
        $("#tp").val(t);
        var form = $("#cp");
        $.validator.unobtrusive.parse(form);
        if (form.valid()) {
            bootbox.confirm({
                message: "Are you sure to add Leave Creadit?",
                buttons: {
                    confirm: {
                        label: 'Yes',
                        className: 'btn-success'
                    },
                    cancel: {
                        label: 'No',
                        className: 'btn-danger'
                    }
                },
                callback: function (result) {
                    if (result == true) {
                        var d = form.serialize();
                        $.ajax({
                            url: '@Url.Action("AddCredit", "Leave")',
                            type: 'POST',
                            data: d,
                            beforeSend: function () {
                                $('.ajax-loader').css("visibility", "visible");
                            },
                            success: function (data) {
                                bootbox.alert({
                                    message: "Leave Credited Successfully!",
                                    callback: function () {
                                        window.parent.location.reload();
                                    }
                                });
                            },
                            error: function (data) {
                                $("#md").replaceWith(data.responseText);
                            },
                            complete: function () {
                                $('.ajax-loader').css("visibility", "hidden");
                            }
                        });
                    }
                }
            });
        }
        return false;
    });
</script>

WebUI/EISSystem/EISSystem/Views/Leave/AddPolicy.cshtml
@using EIS.Entities.Leave
@model LeaveRules

    <link href="~/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <link href="~/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-datetimepicker1.css" rel="stylesheet" />
    <link href="~/css/customStyle.css" rel="stylesheet" />
    <!-- Modal -->
    <style type="text/css">
        .form-group.required .control-label:after {
            color: #d00;
            content: "*";
            position: relative;
        }

        .ajax-loader {
            visibility: hidden;
            position: absolute;
            z-index: +100 !important;
            width: 80%;
            height: 80%;
        }

            .ajax-loader img {
                position: fixed;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
            }
    </style>

    <div id="md" class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <HeaderWithButton class="modal-title" header-name="Add Policy"></HeaderWithButton>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                <div class="ajax-loader">
                    <img src="~/gif/Spinner.gif" />
                </div>
                <form name="cp" id="cp" asp-action="AddPolicy" asp-controller="Leave" method="post">

                    <input type="hidden" asp-for="Id" value="0" />
                    <div class="form-group required">
                        <label class="control-label" asp-for="LeaveType">Leave Type</label>
                        <div class="form-line">
                            <input asp-for="LeaveType" class="form-control" />
                        </div>
                        <span asp-validation-for="LeaveType" class="text-danger"></span>
                    </div>
                    <div class="form-group required">
                        <label class="control-label">Credited to : </label>
                        <select title="Select Employee" id="emps" data-size="5" name="emps" asp-items="@(new SelectList(@ViewBag.Persons,"Id","FirstName"))" class="selectpicker form-control show-tick" data-live-search="true" multiple></select>
                        <span asp-validation-for="LocationId" class="text-danger"></span>
                    </div>
                    <div class="form-group required">
                        <label class="control-label" asp-for="Description"></label>
                        <div class="form-line">
                            <input asp-for="Description" class="form-control" />
                        </div>

                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group required">
                        <label class="control-label">Paid / Unpaid : </label>
                        <select id="isPaid" asp-for="IsPaid" class="form-control show-tick" onchange="MyFun();">
                            <option value="false" id="false">Unpaid</option>
                            <option value="true" id="true" selected>Paid</option>

                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Validity"></label>
                        <div class="form-line">
                            <input asp-for="Validity" id="val" maxlength="2" class="form-control" />
                        </div>
                    </div>
                    <span asp-validation-for="Validity" class="text-danger"></span>
                    <div class="form-group required">
                        <label class="control-label">Valid From</label>
                        <div class="form-line">
                            <input class="form-control" type="text" asp-for="ValidFrom" value="" id="validFrom" placeholder="Select Date" autocomplete="off" />
                        </div>
                        <span asp-validation-for="ValidFrom" class="text-danger"></span>
                    </div>
                    <div class="form-group required">
                        <label class="control-label">Valid To</label>
                        <div class="form-line">
                            <input class="form-control" type="text" asp-for="ValidTo" value="" id="validTo" placeholder="Select Date" autocomplete="off" />
                        </div>
                        <span asp-validation-for="ValidTo" class="text-danger"></span>
                    </div>
                    <div class="modal-footer">
                        <button id="btnSubmit" name="btnSubmit" type="button" class="btn btn-link waves-effect">Create Policy</button>
                        <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="~/plugins/bootstrap-select/js/bootstrap-select.js"></script>

    <script src="~/plugins/momentjs/moment.js"></script>
    <script src="~/Ems/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/js/pages/ui/modals.js"></script>

    <script src="~/plugins/bootbox/bootbox.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>
    $('#emps').selectpicker();
    $('#isPaid').selectpicker();
    var d = new Date();
    d.setDate(d.getDate());
    var defaultDate = moment().toDate();
    $('#validFrom').datetimepicker({
        format: "DD/MMM/YYYY",
        defaultDate: d
    });
    $('#validTo').datetimepicker({
        format: "DD/MMM/YYYY",
        defaultDate: d
    });
    function MyFun() {
        var sel = document.getElementById("isPaid").value;
        if (sel == "false") {
            $("#val").prop("disabled", true);
            $("#val").val("0");
        }
        else {
            $("#val").removeAttr('disabled');
        }
    }
    $('#btnSubmit').click(function () {
        var form = $("#cp");
        $.validator.unobtrusive.parse(form);
        if (form.valid()) {
            bootbox.confirm({
                message: "Are you sure to add new Leave Policy?",
                buttons: {
                    confirm: {
                        label: 'Yes',
                        className: 'btn-success'
                    },
                    cancel: {
                        label: 'No',
                        className: 'btn-danger'
                    }
                },
                callback: function (result) {
                    if (result == true) {
                        var d = form.serialize();
                        $.ajax({
                            /**/
                            url: '@Url.Action("AddPolicy", "Leave")',
                            /**/
                            type: 'POST',
                            data: d,
                            beforeSend: function () {
                                $('.ajax-loader').css("visibility", "visible");
                            },
                            success: function (data) {
                                bootbox.alert({
                                    message: "Policy Added Successfully!",
                                    callback: function () {
                                        window.parent.location.reload();
                                    }
                                });
                            },
                            error: function (data) {
                                $("#md").replaceWith(data.responseText);
                            },
                            complete: function () {
                                $('.ajax-loader').css("visibility", "hidden");
                            }
                        });
                    }
                }
            });
        }
        return false;
    });
    </script>